# -*- coding: utf-8 -*-
"""Accuracy Heatmap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16XiJP2v4JSFY9TIWoxxERlgqlsXA2maE
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Sample data (replace with your actual data)
data = np.array([
    [97.33, 88.48, 30.89],
    [97.33, 89.70, 30.89],
    [96.57, 84.90, 30.89]
])

# Labels for axes
batch_sizes = ["Batch: 16", "Batch: 32", "Batch: 64"]
learning_rates = ["LR: 0.001", "LR: 0.01", "LR: 0.1"]

# Create a heatmap with improved color combinations
plt.figure(figsize=(6, 5))
ax = sns.heatmap(
    data,
    annot=True,
    fmt=".2f",  # Removed the incorrect percentage symbol
    cmap="Blues",  # Change colormap here (options: coolwarm, plasma, magma, cividis)
    linewidths=0.5,
    linecolor="gray",
    annot_kws={"color": "red", "fontsize": 11}
)

# Manually format annotations to add the percentage sign
for text in ax.texts:
    text.set_text(text.get_text() + "%")

# Set axis labels
ax.set_xticklabels(learning_rates)
ax.set_yticklabels(batch_sizes)

# Set labels
plt.xlabel("Learning Rate")
plt.ylabel("Batch Size")
#plt.title("Model Accuracy Heatmap")

# Show plot
plt.show()